// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: identity/events.proto

package identity

import (
	_ "github.com/gauffer/ddd-events-codegen-converters/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_identity_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedEvent) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserCreatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_identity_events_proto protoreflect.FileDescriptor

const file_identity_events_proto_rawDesc = "" +
	"\n" +
	"\x15identity/events.proto\x12\bidentity\x1a\x12common/kafka.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x10UserCreatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt:!\xca\xf3\x18\x1d\n" +
	"\x1bidentity.user_created_eventBGZEgithub.com/gauffer/ddd-events-codegen-converters/pb/identity;identityb\x06proto3"

var (
	file_identity_events_proto_rawDescOnce sync.Once
	file_identity_events_proto_rawDescData []byte
)

func file_identity_events_proto_rawDescGZIP() []byte {
	file_identity_events_proto_rawDescOnce.Do(func() {
		file_identity_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_events_proto_rawDesc), len(file_identity_events_proto_rawDesc)))
	})
	return file_identity_events_proto_rawDescData
}

var file_identity_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_identity_events_proto_goTypes = []any{
	(*UserCreatedEvent)(nil),      // 0: identity.UserCreatedEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_identity_events_proto_depIdxs = []int32{
	1, // 0: identity.UserCreatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_identity_events_proto_init() }
func file_identity_events_proto_init() {
	if File_identity_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_events_proto_rawDesc), len(file_identity_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_events_proto_goTypes,
		DependencyIndexes: file_identity_events_proto_depIdxs,
		MessageInfos:      file_identity_events_proto_msgTypes,
	}.Build()
	File_identity_events_proto = out.File
	file_identity_events_proto_goTypes = nil
	file_identity_events_proto_depIdxs = nil
}
