// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: common/kafka.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_common_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_common_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_common_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var file_common_kafka_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Topic)(nil),
		Field:         51001,
		Name:          "common.topic",
		Tag:           "bytes,51001,opt,name=topic",
		Filename:      "common/kafka.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional common.Topic topic = 51001;
	E_Topic = &file_common_kafka_proto_extTypes[0]
)

var File_common_kafka_proto protoreflect.FileDescriptor

const file_common_kafka_proto_rawDesc = "" +
	"\n" +
	"\x12common/kafka.proto\x12\x06common\x1a google/protobuf/descriptor.proto\"\x1d\n" +
	"\x05Topic\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:F\n" +
	"\x05topic\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x8e\x03 \x01(\v2\r.common.TopicR\x05topicBCZAgithub.com/gauffer/ddd-events-codegen-converters/pb/common;commonb\x06proto3"

var (
	file_common_kafka_proto_rawDescOnce sync.Once
	file_common_kafka_proto_rawDescData []byte
)

func file_common_kafka_proto_rawDescGZIP() []byte {
	file_common_kafka_proto_rawDescOnce.Do(func() {
		file_common_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_kafka_proto_rawDesc), len(file_common_kafka_proto_rawDesc)))
	})
	return file_common_kafka_proto_rawDescData
}

var file_common_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_kafka_proto_goTypes = []any{
	(*Topic)(nil),                       // 0: common.Topic
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_common_kafka_proto_depIdxs = []int32{
	1, // 0: common.topic:extendee -> google.protobuf.MessageOptions
	0, // 1: common.topic:type_name -> common.Topic
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_kafka_proto_init() }
func file_common_kafka_proto_init() {
	if File_common_kafka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_kafka_proto_rawDesc), len(file_common_kafka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_kafka_proto_goTypes,
		DependencyIndexes: file_common_kafka_proto_depIdxs,
		MessageInfos:      file_common_kafka_proto_msgTypes,
		ExtensionInfos:    file_common_kafka_proto_extTypes,
	}.Build()
	File_common_kafka_proto = out.File
	file_common_kafka_proto_goTypes = nil
	file_common_kafka_proto_depIdxs = nil
}
